# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

# Download secure file
# Download a secure file to the agent machine
#    - task: DownloadSecureFile@1
#      name: mySecureFile # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
#      inputs:
#        secureFile: settings.xml # The file name or GUID of the secure file
#    - script: |
#        echo Coping $(mySecureFile.secureFilePath) to the ~/.m2 folder...
#        sudo mkdir ~/.m2/
#        sudo chmod 0777 ~/.m2/
#        sudo cp $(mySecureFile.secureFilePath) ~/.m2/
#        sudo chmod -R 0666 ~/.m2/*
# Download an artifact with name 'com.test:testpackage' to $(System.ArtifactsDirectory)
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        mavenFeedAuthenticate: true
        goals: 'package'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)